---

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: installing rsyslog
  apt: name=rsyslog state=latest

- name: setting up centralised rsyslog
  template: src=rsyslog.conf.j2
            dest=/etc/rsyslog.conf
            owner=root
            group=root
            mode=0644

- name: restart rsyslogd
  service: name=rsyslog state=restarted
  changed_when: False
